name: Auto Comment
on: [issues, pull_request_target]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: >
            HelloğŸ‘‹ @{{ author }}, I hope you are doing well!
            <br>
            Thank you for raising an issue. We will will investigate into the issue and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
            <br>
            Feel free to join the community and collaborate â¤
            <br>
            Join our Discord Community [here](https://discord.gg/fNSts9bvzX)


          pullRequestOpened: >
            HelloğŸ‘‹ @{{ author }}, I hope you are doing well!
            <br>
            Thank you for raising your pull request and contributing to our Community ğŸ‰
            
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
            <br>
            Feel free to join the community and collaborate â¤
            <br>
            Join our Discord Community [here](https://discord.gg/fNSts9bvzX)
